spring:
  profiles:
    active:
      - dev        # ë°ëª¨ìš©ìœ¼ë¡œ dev, prod ê°™ì´ ì¨ë„ ë˜ì§€ë§Œ ë³´í†µì€ í•˜ë‚˜ë§Œ
      - prod
    group:
      dev:
        - debug
        - logging

  main:
    allow-bean-definition-overriding: true
    # ì»¤ìŠ¤í…€ ì •ì  ë¦¬ì†ŒìŠ¤ ìœ„ì¹˜ ì„¤ì •
#  web:
#    resources:
#      static-locations: classpath:/custom-static/

# @Conditional ì‹¤ìŠµìš©
custom:
  feature-enabled: true   # ğŸ‘‰ true/false ë°”ê¾¸ë©´ì„œ Bean ë“±ë¡ ì—¬ë¶€ ë¹„êµí•´ë³´ê¸°

logging:
  level:
    root: INFO